name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # 文本自动生成依赖库 版本默认3.1.0
  english_words: ^3.1.0

  # 从图库选择图片，或用相机拍摄新照片
  image_picker: '>= 0.4.4'

  # 图片加载框架
  #使用NetworkImageWithRetry 代替原生的Image.network 加载网络图片可获得重试能力
  flutter_image: ^1.0.0

  # 支持二维码和条形码扫描
  barcode_scan: '>= 0.0.4'

  # 国际化和本地化设施，包括消息翻译，复数和性别，日期/数字格式和解析以及双向文本。
  intl: ^0.15.6

  # sqlite插件，同时支持ios和andriod。（平台无关）
  sqflite: ^0.9.0

  # Video Player
  video_player: ^0.6.1

  # launching a URL in the mobile platform（浏览器和APP内打开）
  url_launcher: 3.0.2

  #---------------------------- 支付业务相关 --------------------------------
  # 支付宝基础
  flutter_alipay: "^0.1.0"

  #---------------------------- 网络请求相关 --------------------------------
  http: "^0.11.3+16"


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/icon_bg_user_info.png
    - images/icon_charge_alipay.png
    - images/icon_charge_weichat.png
    - images/icon_head_error.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
